# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CXzUtpXYQG2S4feuFLewSl46qpy34frm
"""

from google.colab import files #doc fille du lieu
upload =  files.upload()

from sklearn.datasets import load_iris 
iris_dt=load_iris()
iris_dt.data[1:5]
iris_dt.target[1:5]

#Phan chia du lieu
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dt.data, iris_dt.target, test_size=1/3, random_state=5)
(X_train[1:6])
(X_train[1:6,1:3])
(y_train[1:6])
(X_test[6:10])
(y_test[6:10])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dt.data,iris_dt.target, test_size = 1/3.0,random_state = 5)
(X_train[1:6])

from sklearn.neighbors import KNeighborsClassifier
Mohinh_KNN = KNeighborsClassifier(n_neighbors = 5)
Mohinh_KNN.fit(X_train,y_train)

#du doan nhan cho cac phan tu trong tap kiem tra
y_pred = Mohinh_KNN.predict(X_test)
y_test
Mohinh_KNN.predict([[4,4,3,3]])

#Tính độ chính xác cho giá trị dự đoán của phần tử trong tập kiểm tra
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred, labels=[2,0,1])

"""Giai thuật ngây thơ"""

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
#doc du lieu tu file
import pandas as pd
dulieu = pd.read_csv("iris_data.csv")
X= dulieu.iloc[:,0:4]
y= dulieu.nhan

"""Phân chia du liệu thành tập test và train"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state = 0)
#Xay dung mo hinh dua tren phan phoi xac suat tuan theo Gausian
model = GaussianNB()
model.fit(X_train, y_train)
print(model)
#du doan
thucte = y_test
dubao = model.predict(X_test)
thucte
dubao

"""Sử dụng hàm confusion_matrix() để đánh giá giải thuật"""

from sklearn.metrics import confusion_matrix
cnf_matrix_gnb = confusion_matrix(thucte, dubao)
print(cnf_matrix_gnb)